const SOCKET_JOIN_ROOM = "join_room";

// related to the betting
const SOCKET_BET_GET_DATA = "b/0";
const SOCKET_BET_BET = "b/1";
const SOCKET_BET_JOIN_ROOM = "b/2";
const SOCKET_BET_USER_LOG = "b/3";
const SOCKET_BET_BLOCKING_EVENT = "b/4";
const SOCKET_LOTTERY_STATISTICS = "b/5";
const SOCKET_BET_WARNING_EVENT = "b/6";
const SOCKET_BET_DRWAING_EVENT = "b/7";
const SOCKET_BET_NEWTURN_EVENT = "b/8";
const SOCKET_RECENT_LOTTERY_RESULT = "b/9";
const SOCKET_BET_NEWTURN_EVENT1 = "b/10";
const SOCKET_BET_WARNING_EVENT1 = "b/11";
const SOCKET_BET_DRWAING_EVENT1 = "b/12";
const SOCKET_BET_BLOCKING_EVENT1 = "b/13";

const SOCKET_BET_TABLE_EVENT = "b/14";

// related to the room manager
const SOCKET_CHAT_GET_DATA = "c/0";
const SOCKET_CHAT_JOIN_ROOM = "c/1";
const SOCKET_CHAT_SEND_MESSAGE = "c/2";
const SOCKET_CHAT_RECEIVED_MESSAGE = "c/3";
const SOCKET_CHAT_SENT = "c/4";
const SOCKET_CHAT_USERS_LIST = "c/5";

module.exports = {
  SOCKET_JOIN_ROOM,
  SOCKET_BET_JOIN_ROOM,
  SOCKET_BET_GET_DATA,
  SOCKET_BET_BET,
  SOCKET_BET_USER_LOG,
  SOCKET_BET_BLOCKING_EVENT,
  SOCKET_BET_WARNING_EVENT,
  SOCKET_BET_DRWAING_EVENT,
  SOCKET_BET_NEWTURN_EVENT,
  SOCKET_CHAT_GET_DATA,
  SOCKET_CHAT_JOIN_ROOM,
  SOCKET_CHAT_SEND_MESSAGE,
  SOCKET_CHAT_RECEIVED_MESSAGE,
  SOCKET_CHAT_SENT,
  SOCKET_BET_USER_LOG,
  SOCKET_LOTTERY_STATISTICS,
  SOCKET_CHAT_USERS_LIST,
  SOCKET_RECENT_LOTTERY_RESULT,
  SOCKET_BET_NEWTURN_EVENT1,
  SOCKET_BET_WARNING_EVENT1,
  SOCKET_BET_DRWAING_EVENT1,
  SOCKET_BET_BLOCKING_EVENT1,
  SOCKET_BET_TABLE_EVENT
};
